// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgPdkiIc7i25kgYm8SlWF8MjBqWOO9j4',
    appId: '1:485846725321:web:00e6bc8fc8685d107b5318',
    messagingSenderId: '485846725321',
    projectId: 'simplechat-329aa',
    authDomain: 'simplechat-329aa.firebaseapp.com',
    storageBucket: 'simplechat-329aa.appspot.com',
    measurementId: 'G-V7X2DB3HE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQae1pDgSCOGv4EoSV2IuRZz2srK8VDY4',
    appId: '1:485846725321:android:1e758afb2c57945e7b5318',
    messagingSenderId: '485846725321',
    projectId: 'simplechat-329aa',
    storageBucket: 'simplechat-329aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv02dB5suF5K5usn6WgIMvTFiDwpXW6WY',
    appId: '1:485846725321:ios:7d47d207fbabc6c17b5318',
    messagingSenderId: '485846725321',
    projectId: 'simplechat-329aa',
    storageBucket: 'simplechat-329aa.appspot.com',
    iosClientId: '485846725321-b4lr0ht3kvbirjddbhu81vd5n60l4631.apps.googleusercontent.com',
    iosBundleId: 'com.ricky-hu.simpleChat',
  );
}
